### ISSUE TITLE
FAILURE : THINGSBOARD javascript executor Microservice

### ISSUE THREAD

**Issue by m0o0hammad** [thingsboard/thingsboard#1412]
This error happends when i compile thingsboard 2.2.0
![screenshot from 2019-01-21 01-02-15](https://user-images.githubusercontent.com/30108318/51516217-d8b9e800-1e2b-11e9-9298-c4ded07a4059.png)

please help

**Comment by absinthetized** [comment]
do as suggested by error messages: run maven with the -e wsitch to have a proper backtrace.

**Comment by m0o0hammad** [comment]
@absinthetized  
$ mvn clean install -DskipTests -e

[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [01:27 min]
[INFO] Netty MQTT Client .................................. SUCCESS [  7.662 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.193 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  9.174 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.625 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  2.123 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.076 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  7.303 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.784 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.884 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.222 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 20.037 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.080 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.606 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 16.302 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.341 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 21.091 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 16.030 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 13.607 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [07:27 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  2.396 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [01:38 min]
[INFO] ThingsBoard Microservices .......................... SUCCESS [ 32.224 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [ 15.599 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... FAILURE [ 23.875 s]
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:53 min
[INFO] Finished at: 2019-01-24T13:49:48+03:30
[INFO] Final Memory: 92M/476M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (assembly) on project js-executor: Failed to create assembly: Error adding file to archive: /home/mamoit/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (assembly) on project js-executor: Failed to create assembly: Error adding file to archive: /home/mamoit/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error adding file to archive: /home/mamoit/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:530)
	at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute(SingleAssemblyMojo.java:58)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugins.assembly.archive.ArchiveCreationException: Error adding file to archive: /home/mamoit/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.plugins.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:131)
	at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
	at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:476)
	... 23 more
Caused by: java.nio.file.NoSuchFileException: /home/mamoit/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Unix.readAttributes(UnixFileAttributeViews.java:345)
	at sun.nio.fs.AbstractFileSystemProvider.readAttributes(AbstractFileSystemProvider.java:92)
	at java.nio.file.Files.readAttributes(Files.java:1964)
	at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.<init>(Java7FileAttributes.java:65)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPathJava7(PlexusIoResourceAttributeUtils.java:336)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPath(PlexusIoResourceAttributeUtils.java:198)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributes(PlexusIoResourceAttributeUtils.java:175)
	at org.codehaus.plexus.components.io.resources.ResourceFactory.createResource(ResourceFactory.java:40)
	at org.apache.maven.plugins.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:120)
	... 25 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :js-executor

**Comment by asnik** [comment]
The same on Ubuntu 16.04lts. I have commented assembly plugin in a few pom.xml and build is finished then. But 'White label' page is shown in browser when i stard thingsboard service.

**Comment by absinthetized** [comment]
Maven is idiod: you have to pass the -X switch also as the log is truncated
and we miss the root cause :/

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Mobile: 3351613944

Il giorno gio 24 gen 2019, 13:55 Anton Nikitin <notifications@github.com>
ha scritto:

**Comment by m0o0** [comment]
@asnik 
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <finalName>${pkg.name}</finalName>
                    <descriptors>
                        <descriptor>src/main/assembly/windows.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
</plugin>
You 've deleted this area?

**Comment by m0o0** [comment]
@asnik  You 've deleted this area?
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <finalName>${pkg.name}</finalName>
                    <descriptors>
                        <descriptor>src/main/assembly/windows.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
</plugin>

**Comment by m0o0** [comment]
@asnik  You 've deleted this area?
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <finalName>${pkg.name}</finalName>
                    <descriptors>
                        <descriptor>src/main/assembly/windows.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
</plugin>`

**Comment by asnik** [comment]
@m0o0hammad Yes, i have commented this text. But still did not get working package build.

**Comment by absinthetized** [comment]
Are you trying to build windows from linux? This is a windows exe error!

**Comment by asnik** [comment]
@absinthetized I do not need windows) But build process is trying to build all platforms as i guess.
I need just .deb package and also wonder of this error.

**Comment by asnik** [comment]
I've got success build of v.2.2 on Ubuntu 16.04lts, seems like working. So only 2 changes for build:
1. To avoid Permission access error for git clone I've replaced in pom.xml (not just one, but for all problem modules) npmVersion 6.4.1 for 3.10.8 as was mentioned in other issue. I do not understand why 3.10.8, is it really good or not, but working (not full tested yet).
2. To avoid windows exe error i've excluded maven-assembly-plugin from pom.xmls as also was mentioned in other issue.

**Comment by absinthetized** [comment]
Happy you have solved but these are workarounds fixes are still missing :/

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Mobile: 3351613944

Il giorno gio 24 gen 2019, 19:18 Anton Nikitin <notifications@github.com>
ha scritto:

**Comment by asnik** [comment]
@m0o0hammad  yes. try to change msa/web-ui/pom.xml and msa/js-executor/pom.xml

**Comment by absinthetized** [comment]
OT. Holy crap! gmail does a terrible job at reply messages!

**Comment by m0o0hammad** [comment]
Thanks, the problem was resolved and the server was running well.
@asnik @absinthetized

**Comment by CharlotteEGM** [comment]
> 
> 
> The same on Ubuntu 16.04lts. I have commented assembly plugin in a few pom.xml and build is finished then. But 'White label' page is shown in browser when i stard thingsboard service.

Hi, I also have the same problem on building 2.4.0 : I have commented assembly plugin, the build is done, but then I have white label error...
I don't understand in the following replies how did you overcome this issue ?

**Comment by SebastianHerr** [comment]
Hello, when i was trying to build this from source i ran into the same issue and while removing the windows build from the config files can succed in running maven install it does not solve the underlying issue. Way up in my logs i had a error that npm install did not succed and did not create this required exe, the line giving the hint was: 
`npm WARN lifecycle thingsboard-web-ui@2.4.3~install: cannot run in wd thingsboard-web-ui@2.4.3 pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js (wd=/.../thingsboard/thingsboard/msa/web-ui)`
This has been fixed by using a workaround mentioned here: https://til.codes/npm-install-failed-with-cannot-run-in-wd-2/
I added " --unsafe-perm" in "\thingsboard\msa\js-executor\pom.xml" and "\thingsboard\msa\web-ui\pom.xml" to the arguments.
This is the resulting bit of the pom.xml:
`...
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <arguments>install --unsafe-perm</arguments>
    </configuration>
</execution>
...`

I hoped this will help someone running into the same kind of issue

**Comment by anupa1235** [comment]
I am not able to solve this issue with thingsboard -3.0.Can you please guide me. @m0o0hammad

**Comment by zacky131** [comment]
> I am not able to solve this issue with thingsboard -3.0.Can you please guide me. @m0o0hammad

Hi, at last i am able to install TB 3.2 from source on ubuntu 20.04.
You can refer to this #3330  [link](https://github.com/thingsboard/thingsboard/issues/3330#issuecomment-752366380l)

Hope it helps :)
