### ISSUE TITLE
RBAC: Permission denied only on first login attempt

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#2418]
Hello. I have the following configuration setup for an end-user:
- User A belongs to Customber A, in group mUsers.
- mUsers have permission to Read all features that they need to access and view.
- mUsers don't have "Read" permission for Dashboard on their Generic Role, as I don't want User A to be able to view dashboards from Customer A. (Customer A has admin-level dashboards that end users shouldn't see)
- mUsers has Read-only Group permission for a Dashboard Group A from Tenant A. I share this group with all customer users as it is a generic dashboard. 
- User A has Dashboard A from this Dashboard Group A, as default dashboard and it opens in fullscreen.

Expected:
When I login with User A, it should open Dashboard A in fullscreen, as it is being shared with Read Only Role. 

Actual:
The first time I attempt to login with User A, the "Permission Denied" pop-up shows and login fails. HOWEVER, if I retry the login immediatelly after, it does login properly and I can view the dashboard fine. If I refresh later on the page, while on the dashboard, it pops the Permission Denied message again and logs me out.

Notes:
- The problem persists even if I don't use "Always in fullscreen".
- If I attempt the same, with giving Group Permission Read Only for a Dashboard Group from Customer A (Without Generic Read permission for Dashboards), the same things happends for User A. I don't know if this is expected behaviour or a bug.
Any suggestions on what the problem might be? So far, it all points at this being a bug.

**Comment by ashvayka** [comment]
How do you login with this user? You use "impersonate" icon (switch from Tenant user to Customer user) or do completely fresh login? Also, what version are you using? There were some critical fixed in 2.4.3

**Comment by Manusisko** [comment]
Hi Andrew. I login with a fresh login, everytime. And I'm using version 2.3.1
Can you confirm this is fixed on 2.4.3?

**Comment by Manusisko** [comment]
As of March 20th, this is still an issue, even on version 2.4.3
A Customer cannot have different groups of users which have restricted access to some dashboards from the Client's ownership. In order for a User to be able to see any dashboard at all, the MUST have access to EVERY dashboard that their Customer owns, as Generic Role "READ" on Dashboards is required to see a dashboard, and this role also enables to user to see all dashboards at or beneath is hierarchy.

**Comment by ssakharova** [comment]
Hello @Manusisko,
Could you tell me please the problem is still relevant?

Regards
