### ISSUE TITLE
Unable to save data-key configuration via user-interface when editing a Flot chart

### ISSUE THREAD

**Issue by VecchioIdraulico** [thingsboard/thingsboard#328]
# **Steps to reproduce:**
1. Set up Thingsboard such that it has a working telemetry source.
1. Insert a Flot chart into the dashboard.
1. Add parameters.
1. Attempt to configure a data-key through its edit icon (the pencil):  Change any value, or add a post-processing function.
1. Note that the **Save** button remains inactive.

# **Expected results:**
One should be able to save the changes made to the Flot configuration.

# **Actual results:**
The configuration cannot be saved through the interface.

# **More information:**
The chart can be configured successfully by editing its exported configuration, deleting the widget, and replacing it with an import of the edited version.

**Comment by ikulikov** [comment]
Fixed in the master branch. Will be available in release v1.3.1.

**Comment by sazalihisham88** [comment]
Hi @ikulikov 

May I know the commit id for this fix so I can patch it myself? I am on the version where this issue is still there and currently not ready to update the version for a certain reason. Many thanks!
