### ISSUE TITLE
[Bug] WebSocket Error: Too many updates!

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3725]
**Describe the bug**
When I open a dashboard which has large number of devices, I see this error:

WebSocket Error: Too many updates!

I have looked for this error information, but it is not clear why it should come on the client browser side.
Is a resource allocation issue for the Cloud setup?

**Your Server Environment**

* own setup
  * Cloud 
  * ThingsBoard Version : CE 3.0.1
  * OS Name and Version : Ubuntu 18.04 LTS

**Your Client Environment**

MacOS Mini, 16GB

* OS: MacOS Catalina 10.15.7
* Browser Chrome
* Version 86.0.4240.198 

**Screenshots**
Catalina 10.15.7
![image](https://user-images.githubusercontent.com/55399007/99190079-68273e00-2719-11eb-9342-f8e1948532cb.png)

**Comment by ysit-thingsboard** [comment]
Try to update this configuration:

![image](https://user-images.githubusercontent.com/71913697/99226231-6007f500-2824-11eb-93cf-1ddb291d3e22.png)

**Comment by ashvarma-git** [comment]
Thank you for your reply.
Which file is this setting in?
And I guess I need to restart the Thingsboard service after making this change.

**Comment by ashvarma-git** [comment]
I found the thingboard.yml file. Current setting is:

      max_updates_per_session: "${TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION:300:1,3000:60}"

What is the meaning of these numbers and what should I try to change to?
Will I need to recompile the .jar after this change or do I just restart the thingboard service?

**Comment by ashvarma-git** [comment]
What is the best way to do it through /etc/thingsboard/conf/thingsboard.yml or /etc/thingsboard/conf/thingsboard.conf so that I don't have to recompile the Java app?

**Comment by ashvarma-git** [comment]
I did as recommended above by creating /etc/thingsboard/conf/thingsboard.conf with this single line:

export TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION=10000:1,30000:60

I restarted thingsboard service.

But I still continue to get the WebSocket Error: Too many updates!

**Comment by quocnh** [comment]
did you solve this problem?

**Comment by vvlladd28** [comment]
Hi @quocnh,
This problem has been fixed in TB 3.1.0

**Comment by quocnh** [comment]
@ashvayka I am still get this issues with this PE (thingsboard-3.3.1pe.deb) version. I have sent an email to thingsboard to ask about that.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION is a parameter for configuration websocket limits.
