### ISSUE TITLE
Problems with RPC control widgets

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#438]
While using the various control widgets, I found out that lots of errors are happening. The switches are not representing the actual state, the command issued is not properly acknowledged etc...

My proposition:
- When a dashboard opens, before getting the response of the first getValue RPC, the widget should show something like "Loading".
- When the initial getValue fails, the dashboard should retry periodically.
- Even if everything is OK, a periodic getValue should be sent, ensuring that the dahsboard shows what is actually set to the device.
- When a setValue is issued, it should be followed with a get value to ensure the result. During this communication a "Loading" message should appear. If any of the above steps fails, show an error, and continue retry getValue RPCs.

Please keep in mind that:
- A dashboard with lots of such widgets may take ages to load. During this time, the widgets possibly show the wrong value, confusing the user.
- A device that was initially OK, may die while the dashboard is open.
- A device that was dead when the dashboard was open may get connected again soon.
- An RPC request may not be possible to be executed successfully for a great variety of causes.
- Since a getValue is issued only once, later another user (or anything outside the scope of thingsboard), may alter this value. The initial dashboard will continue to show the wrong value indefinitely.

**Comment by ashvayka** [comment]
This are valid requests. We should crate Jira issue from this. @mp-loki please comment.

**Comment by fotis400** [comment]
@ashvayka are there any news regarding the mentioned issues?

**Comment by LeoMorgan113** [comment]
Hi @431,
Is this issue still actual?

**Comment by fotis400** [comment]
Hi @LeoMorgan113,

yes, of course they are still actual.  
AFAIK none of these points have been addressed in any of the TB releases of the last 4 years.

RPC's from widgets remain very unreliable.

**Comment by LeoMorgan113** [comment]
@fotis400 

I've added your suggestion to our backlog(PROD-1032). It will be review by our developers, and in case of approval, will be implemented as soon as possible.

**Comment by Ultrazombie** [comment]
@fotis400 I have pushed this issue again to our developers and if this is introduced, keep an eye on our release notes.

**Comment by fjpanag** [comment]
@Ultrazombie None of the above has been fixed, and it is considered a valid issue as I see in the comments above.

The dashboards have the potential to display false information.

The issue is standing from 2017 and now it is discarded?

**Comment by Ultrazombie** [comment]
@fjpanag 
No, it's not solved. I'm re-opening a ticket because this problem is not solved.

**Comment by mykhailokornieiev** [comment]
Hi. Thank you for the suggestion. Such a feature request was previously added to our backlog for developers. So far, there is no estimated time for this improvement. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases. We're closing this ticket to keep our repository well-maintained and focused on active issues.
We appreciate your patience and understanding.
