### ISSUE TITLE
Raspberry pi3 instalation error

### ISSUE THREAD

**Issue by Gargantuanman** [thingsboard/thingsboard#883]
Yesterday i tried to install thingsboard 2.0.3 to my rpi3 i followed the instructions but when i execute the command: sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

the prompt says: Unrecognized VM option 'UseCondCardMark'
error: Could not créate Java Virtual Machine.

Could you help me please?

Yesterday I found someo with the same issue and say its because new Raspian updated some components and it affect the new 2.0.3 versión of thingsboard.

Thank you.

**Comment by vparomskiy** [comment]
What jvm version is installed on rpi3?

**Comment by Gargantuanman** [comment]
if I type: java -versión i get:

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

**Comment by Gargantuanman** [comment]
Im using Raspbian Stretch with desktop

Image with desktop based on Debian Stretch
Version:
April 2018
Release date:
2018-04-18
Kernel version:
4.14

**Comment by vparomskiy** [comment]
Please upgrade java to the latest version. It should resolve this issue

**Comment by vparomskiy** [comment]
I mean to the latest 1.8.x version

**Comment by Gargantuanman** [comment]
Now i have the versión 1.8.0_171 but still have the same error

**Comment by vparomskiy** [comment]
this flag is available on the server JVM. I think that your JVM started in the **client** mode. We will resolve this issue in the next release, but for now, you have 2 options for workaround the issue:
1. Remove -XX:+UseCondCardMark JVM flag from thingsboard.conf file
2. Or you can add -XX:+IgnoreUnrecognizedVMOptions JVM flag in the thingsboard.conf file

thingsboard.conf file can be found in this directory:
/etc/thingsboard/conf/thingsboard.conf

**Comment by Gargantuanman** [comment]
Hi, with the IgnoreVM Options I sucessfully instaled thingsboard and now i proceed to test it. thank you very much
